baseurl = "http://wanglijuan.com/"
languageCode = "zh-cn"
title = "设计∙人生"
theme = "icarus"
paginate = 6

[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    author = "欧巴塞罗那"
    bio = "设计师 - 吃货 - 爱玩"
    location = "Su Zhou"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [icarus](https://github.com/digitalcraftsman/hugo-icarus-theme)."
    avatar = "css/images/avatar.png"
    # Format dates with Go's time formatting
    date_format = "2006/01/02"


# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

[[params.menu]]
    before = false
    label  = "About"
    link   = "about/"

# Enter a link for the follow button on the left
[params.profile]
   follow_button = "http://weibo.com/laoshiduanzi"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    weibo           = "laoshiduanzi"
    qq              = "1009255715"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

